package:
  name: scaffoldgraph
  version: 1.0.2

source:
  path: ../

build:
  number: 0
  script: "$PYTHON setup.py install --single-version-externally-managed --record=/tmp/record.txt"  [not-win]
  script: "%PYTHON% setup.py install"  [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - rdkit
    - networkx
    - scipy
    - pandas
    - tqdm
    - loguru
    - pytest

  test:
    imports:
      - scaffoldgraph

    requires:
      - pytest
      - coverage
      - pytest-cov

about:
  home: https://github.com/uclcheminformatics/scaffoldgraph
  license: MIT
  summary: ScaffoldGraph is an open-source library, for generating scaffold networks and scaffold trees.

